from  selenium import webdriver
from  selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
driver=webdriver.Chrome("C:\\Users\\conta\\OneDrive\\Desktop\\jishnu\\chromedriver.exe")
driver.get("https://www.dummyticket.com/dummy-ticket-for-visa-application/")
driver.find_element(by=By.ID,value="product_551").click()
driver.find_element(by=By.ID,value="travname").send_keys("jishnu")
driver.find_element(by=By.ID,value="travlastname").send_keys("vs")
driver.find_element(by=By.ID,value="sex_1").click()
driver.find_element(by=By.CLASS_NAME,value="checkbox").click()
# ss=driver.find_elements_by_xpath("//*[@id='addpaxno_field']/span/span/span[1]/span/span[2]/b")
# dd=Select(ss).select_by_visible_text("option1")
driver.find_element(by=By.ID,value="traveltype_2").click()
driver.find_element(by=By.ID,value="fromcity").send_keys("kozhikode")
driver.find_element(by=By.ID,value="tocity").send_keys("goa")
ww=driver.find_element(by=By.ID,value="reasondummy")
aa=Select(ww)
aa.select_by_visible_text("Prank a friend")
driver.find_element(by=By.ID,value="deliverymethod_3").click()
driver.find_element(by=By.ID,value="billname").send_keys("aaaaa")
driver.find_element(by=By.ID,value="billing_phone").send_keys("9048869977")
driver.find_element(by=By.ID,value="billing_email").send_keys("jishnu@gmail.com")
zz=driver.find_element(by=By.ID,value="billing_country")
qq=Select(zz)
qq.select_by_index(3)
driver.find_element(by=By.ID,value="billing_address_1").send_keys("askhfsjw,hgf.khqg")
driver.find_element(by=By.ID,value="billing_address_2").send_keys("dgfqhagdf")
driver.find_element(by=By.ID,value="billing_city").send_keys("kozhikode")
driver.find_element(by=By.ID,value="billing_postcode").send_keys("673603")